# Stage 1: Build the application
FROM node:20-alpine AS build

ARG VITE_REGISTRY_URL
ARG VITE_SCOPE_MANAGER_URL
ARG VITE_COLLECTOR_EVENTS_URL
ARG VITE_ASSETS_MANAGER_URL
ARG VITE_DASHBOARD_URL
ARG VITE_REPORTER_URL
ARG VITE_DIRECTOR_URL

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Set environment variables for Vite
ENV VITE_REGISTRY_URL=$VITE_REGISTRY_URL
ENV VITE_SCOPE_MANAGER_URL=$VITE_SCOPE_MANAGER_URL
ENV VITE_COLLECTOR_EVENTS_URL=$VITE_COLLECTOR_EVENTS_URL
ENV VITE_ASSETS_MANAGER_URL=$VITE_ASSETS_MANAGER_URL
ENV VITE_DASHBOARD_URL=$VITE_DASHBOARD_URL
ENV VITE_REPORTER_URL=$VITE_REPORTER_URL
ENV VITE_DIRECTOR_URL=$VITE_DIRECTOR_URL

RUN npm run build

# Stage 2: Serve the application
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]


